### ISSUE TITLE
Support for Organizations

### ISSUE THREAD

**Issue by rootux** [Edgeryders-Participio/multi-dreams#58]
# Description
Implement Organizations as owners of `Events` and connected to `Users`
At the moment - Membership are on the event level. Users -> Events

# Tasks
- [x] Database changes (See next section below)
- [x] Set up ability to set domains[?] (Main domain - dreams.wtf Subdomains - borderland.dreams.wtf Custom domains)
- [x] When loading events - make sure we are loading events only for the specific organization
- [x] Handling setting `organization` through the url (To support guest users) - This might be an issue as borderland.dream.wtf can be aliased by someone to be borderland.com
- [x] Security - right now we are validating that a user `isOrgAdmin` - Now we should check which organization that user is assigned to and also if he is org admin.
- [x] Creating a user changes depending on which organization the user is currently at
- [ ] Create a backend user interface to allow Deleting an organization
- [ ] Create a backend user interface to allow Adding a new organization
- [ ] [Migrate existing users to a mother organization?] @aerugo @skoteskote ?

# Database changes
- [x] Change users model to holds organizationId which would link a user to
an organization. organizationId Can't be null.
- [x] Change event model to holds organizationId

> Organization
id - Mongo's Object id
name - String - Borderland
subdomain - String - For example borderland (As to borderland.dreams.wtf)

# Other notes

No need to see all organizations bird eye view
Linked to https://miro.com/app/board/o9J_ktbysWs=/

# Questions

~~1. Do we already have some admin backend interface @gustavlrsn ?~~
2. How does deleting an organization done (Should we limit it in any way - for example only if the organization has no dreams)?
~~3. Who can create / delete an organization? I assume root admin of some kind? @aerugo @skoteskote ~~
~~4. What's the best place to inject subdomain into the app - A short call with @gustavlrsn is needed~~
5. What happens if I don't have an organization and going directly to the root website?

**Comment by rootux** [comment]
@gustavlrsn Since `orgnization` are going to be core - I was thinking about adding it to the `Apollo server` `context` - similar to how we have `currentUser` - so we don't have to get it every time - When we extract `currentUser` (in `api/index.js` we can also extract the organization).
What do you think?

**Comment by rootux** [comment]
Also @gustavlrsn do you have any experience navigating through creating those subdomains?

**Comment by gustavlrsn** [comment]
> @gustavlrsn Since `orgnization` is going to be core - I was thinking about adding it to the `Apollo server` `context` - similar to how we have `currentUser` - so we don't have to get it every time - When we extract `currentUser` (in `api/index.js` we can also extract the organization).
> What do you think?

Great idea. Let's do that.

**Comment by gustavlrsn** [comment]
> Also @gustavlrsn do you have any experience navigating through creating those subdomains?

In a previous version the events was available on subdomains, it was easy to set up a "wildcard domain" on Vercel.  and then you could extract the subdomain out of the request in the frontend. 

> but I understood we are changing environments to `gcloud`?

We have talked about trying Azure, deploying a Dokku instance (https://github.com/Edgeryders-Participio/multi-dreams/issues/56) and let it take care of the wildcard domain handling (and should be easy to deploy anywhere)

**Comment by rootux** [comment]
> In a previous version the events was available on subdomains, it was easy to set up a "wildcard domain" on Vercel. and then you could extract the subdomain out of the request in the frontend.

Good to hear.

> We have talked about trying Azure, deploying a Dokku instance (#56) and let it take care of the wildcard domain handling (and should be easy to deploy anywhere)

Got it. Okay. I'll wait with subdomains for now as it looks like those depends on a success migration

**Comment by rootux** [comment]
As to backend admin interface (For managing Organizations) -
The requirements are - Allow CRUD operations on the models (Such as Organisations (Or other future models) ).
Perhaps allow to call some special mutation with a user input (Like a migration of data from one organization to another)

There are 3 methods here
First - Since it's for root admin - let it work using a mongo editor / graphql playground - Cumbersome, error prune - but works and doesn't require any infrastructure.
Second would be to build something of ourselves - Time consuming, Another part that needs to be maintened.
Third would be to use an existing framework. Some candidates (Ranked from top to bottom) are:
* [Strapi](https://github.com/strapi/strapi)
* [Keystonejs](https://www.keystonejs.com/)
* [Admin-Bro](https://adminbro.com/)
* [React Admin](https://github.com/marmelab/react-admin)
* [Crudl.io](https://crudl.io/)

Going with one of the above would require specific knowledge and would create a strong dependency on that solution.
Would love to hear your take on it @gustavlrsn @aerugo @skoteskote

**Comment by gustavlrsn** [comment]
> First - Since it's for root admin - let it work using a mongo editor / graphql playground - Cumbersome, error prune - but works and doesn't require any infrastructure.

I think this sounds reasonable to start with, since its already there, and then we can add something nicer later

**Comment by aerugo** [comment]
Yeah, I agree with @gustavlrsn. We won't create orgs very often for the first 6-12 months, so let's go for the simplest solution.
