### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by gustavlrsn** [Edgeryders-Participio/multi-dreams#9]
Flags assist in decentralizing the dreams screening/review process to make sure they meet the guidelines for the dreams granting. 

## User stories
- As an event admin I want to define these flags
- As an event member I would like to raise (or take down) these flags, including a comment
  - ... I would like to approve a dream
  - ... I would like to see how many flags are raised for each flag and how many approvals there are

Screenshot of the flags/"monsters" from Dreams 1.0:
<img width="758" alt="Skärmavbild 2020-01-23 kl  14 03 55" src="https://user-images.githubusercontent.com/1552194/72986833-5b7fd500-3de9-11ea-8f96-f953b1a6ce9f.png">

## Tasks

- [x] Implement a modals in the settings for about text, guideline and flag setting
- [x] Define guidelines one by one on event level
- [x] Implement flagging and monster prompt, let each guideline field correspond to a flag
